// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _CleanupCustomerDataEp } from '../src/api/cleanupCustomerData';
import type { default as _CreateAccommodationEp } from '../src/api/createAccommodation';
import type { default as _CreateBookingEp } from '../src/api/createBooking';
import type { default as _CreateCustomerEp } from '../src/api/createCustomer';
import type { default as _CreateDestinationEp } from '../src/api/createDestination';
import type { default as _CreatePackageEp } from '../src/api/createPackage';
import type { default as _CreatePassengerEp } from '../src/api/createPassenger';
import type { default as _CreatePaymentEp } from '../src/api/createPayment';
import type { default as _CreateReviewEp } from '../src/api/createReview';
import type { default as _CreateTransportationEp } from '../src/api/createTransportation';
import type { default as _DeleteAccommodationEp } from '../src/api/deleteAccommodation';
import type { default as _DeleteBookingEp } from '../src/api/deleteBooking';
import type { default as _DeleteCustomerEp } from '../src/api/deleteCustomer';
import type { default as _DeleteDestinationEp } from '../src/api/deleteDestination';
import type { default as _DeletePackageEp } from '../src/api/deletePackage';
import type { default as _DeletePassengerEp } from '../src/api/deletePassenger';
import type { default as _DeletePaymentEp } from '../src/api/deletePayment';
import type { default as _DeleteReviewEp } from '../src/api/deleteReview';
import type { default as _DeleteTransportationEp } from '../src/api/deleteTransportation';
import type { default as _GetAccommodationsEp } from '../src/api/getAccommodations';
import type { default as _GetBookingsEp } from '../src/api/getBookings';
import type { default as _GetBookingsAndCustomersEp } from '../src/api/getBookingsAndCustomers';
import type { default as _GetCustomersEp } from '../src/api/getCustomers';
import type { default as _GetDashboardDataEp } from '../src/api/getDashboardData';
import type { default as _GetDestinationsEp } from '../src/api/getDestinations';
import type { default as _GetIncomeDataEp } from '../src/api/getIncomeData';
import type { default as _GetPackagesEp } from '../src/api/getPackages';
import type { default as _GetPassengersEp } from '../src/api/getPassengers';
import type { default as _GetPaymentsEp } from '../src/api/getPayments';
import type { default as _GetPaymentsAndBookingsEp } from '../src/api/getPaymentsAndBookings';
import type { default as _GetReportsDataEp } from '../src/api/getReportsData';
import type { default as _GetReviewsEp } from '../src/api/getReviews';
import type { default as _GetTransportationEp } from '../src/api/getTransportation';
import type { default as _ImportLegacyCustomersEp } from '../src/api/importLegacyCustomers';
import type { default as _LoginEp } from '../src/api/login';
import type { default as _PopulateApplicationDataEp } from '../src/api/populateApplicationData';
import type { default as _UpdateAccommodationEp } from '../src/api/updateAccommodation';
import type { default as _UpdateBookingEp } from '../src/api/updateBooking';
import type { default as _UpdateCustomerEp } from '../src/api/updateCustomer';
import type { default as _UpdateDestinationEp } from '../src/api/updateDestination';
import type { default as _UpdatePackageEp } from '../src/api/updatePackage';
import type { default as _UpdatePaymentEp } from '../src/api/updatePayment';
import type { default as _UpdateTransportationEp } from '../src/api/updateTransportation';

type _CleanupCustomerDataCfg = typeof _CleanupCustomerDataEp;
export type CleanupCustomerDataInputType = NonNullable<_CleanupCustomerDataCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CleanupCustomerDataCfg['execute']>[0]['input'];
export type CleanupCustomerDataOutputType = Awaited<ReturnType<_CleanupCustomerDataCfg['execute']>>;
export const cleanupCustomerData = createCaller<CleanupCustomerDataInputType, CleanupCustomerDataOutputType>('cleanupCustomerData');

type _CreateAccommodationCfg = typeof _CreateAccommodationEp;
export type CreateAccommodationInputType = NonNullable<_CreateAccommodationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateAccommodationCfg['execute']>[0]['input'];
export type CreateAccommodationOutputType = Awaited<ReturnType<_CreateAccommodationCfg['execute']>>;
export const createAccommodation = createCaller<CreateAccommodationInputType, CreateAccommodationOutputType>('createAccommodation');

type _CreateBookingCfg = typeof _CreateBookingEp;
export type CreateBookingInputType = NonNullable<_CreateBookingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateBookingCfg['execute']>[0]['input'];
export type CreateBookingOutputType = Awaited<ReturnType<_CreateBookingCfg['execute']>>;
export const createBooking = createCaller<CreateBookingInputType, CreateBookingOutputType>('createBooking');

type _CreateCustomerCfg = typeof _CreateCustomerEp;
export type CreateCustomerInputType = NonNullable<_CreateCustomerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateCustomerCfg['execute']>[0]['input'];
export type CreateCustomerOutputType = Awaited<ReturnType<_CreateCustomerCfg['execute']>>;
export const createCustomer = createCaller<CreateCustomerInputType, CreateCustomerOutputType>('createCustomer');

type _CreateDestinationCfg = typeof _CreateDestinationEp;
export type CreateDestinationInputType = NonNullable<_CreateDestinationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateDestinationCfg['execute']>[0]['input'];
export type CreateDestinationOutputType = Awaited<ReturnType<_CreateDestinationCfg['execute']>>;
export const createDestination = createCaller<CreateDestinationInputType, CreateDestinationOutputType>('createDestination');

type _CreatePackageCfg = typeof _CreatePackageEp;
export type CreatePackageInputType = NonNullable<_CreatePackageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreatePackageCfg['execute']>[0]['input'];
export type CreatePackageOutputType = Awaited<ReturnType<_CreatePackageCfg['execute']>>;
export const createPackage = createCaller<CreatePackageInputType, CreatePackageOutputType>('createPackage');

type _CreatePassengerCfg = typeof _CreatePassengerEp;
export type CreatePassengerInputType = NonNullable<_CreatePassengerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreatePassengerCfg['execute']>[0]['input'];
export type CreatePassengerOutputType = Awaited<ReturnType<_CreatePassengerCfg['execute']>>;
export const createPassenger = createCaller<CreatePassengerInputType, CreatePassengerOutputType>('createPassenger');

type _CreatePaymentCfg = typeof _CreatePaymentEp;
export type CreatePaymentInputType = NonNullable<_CreatePaymentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreatePaymentCfg['execute']>[0]['input'];
export type CreatePaymentOutputType = Awaited<ReturnType<_CreatePaymentCfg['execute']>>;
export const createPayment = createCaller<CreatePaymentInputType, CreatePaymentOutputType>('createPayment');

type _CreateReviewCfg = typeof _CreateReviewEp;
export type CreateReviewInputType = NonNullable<_CreateReviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateReviewCfg['execute']>[0]['input'];
export type CreateReviewOutputType = Awaited<ReturnType<_CreateReviewCfg['execute']>>;
export const createReview = createCaller<CreateReviewInputType, CreateReviewOutputType>('createReview');

type _CreateTransportationCfg = typeof _CreateTransportationEp;
export type CreateTransportationInputType = NonNullable<_CreateTransportationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateTransportationCfg['execute']>[0]['input'];
export type CreateTransportationOutputType = Awaited<ReturnType<_CreateTransportationCfg['execute']>>;
export const createTransportation = createCaller<CreateTransportationInputType, CreateTransportationOutputType>('createTransportation');

type _DeleteAccommodationCfg = typeof _DeleteAccommodationEp;
export type DeleteAccommodationInputType = NonNullable<_DeleteAccommodationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteAccommodationCfg['execute']>[0]['input'];
export type DeleteAccommodationOutputType = Awaited<ReturnType<_DeleteAccommodationCfg['execute']>>;
export const deleteAccommodation = createCaller<DeleteAccommodationInputType, DeleteAccommodationOutputType>('deleteAccommodation');

type _DeleteBookingCfg = typeof _DeleteBookingEp;
export type DeleteBookingInputType = NonNullable<_DeleteBookingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteBookingCfg['execute']>[0]['input'];
export type DeleteBookingOutputType = Awaited<ReturnType<_DeleteBookingCfg['execute']>>;
export const deleteBooking = createCaller<DeleteBookingInputType, DeleteBookingOutputType>('deleteBooking');

type _DeleteCustomerCfg = typeof _DeleteCustomerEp;
export type DeleteCustomerInputType = NonNullable<_DeleteCustomerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteCustomerCfg['execute']>[0]['input'];
export type DeleteCustomerOutputType = Awaited<ReturnType<_DeleteCustomerCfg['execute']>>;
export const deleteCustomer = createCaller<DeleteCustomerInputType, DeleteCustomerOutputType>('deleteCustomer');

type _DeleteDestinationCfg = typeof _DeleteDestinationEp;
export type DeleteDestinationInputType = NonNullable<_DeleteDestinationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteDestinationCfg['execute']>[0]['input'];
export type DeleteDestinationOutputType = Awaited<ReturnType<_DeleteDestinationCfg['execute']>>;
export const deleteDestination = createCaller<DeleteDestinationInputType, DeleteDestinationOutputType>('deleteDestination');

type _DeletePackageCfg = typeof _DeletePackageEp;
export type DeletePackageInputType = NonNullable<_DeletePackageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeletePackageCfg['execute']>[0]['input'];
export type DeletePackageOutputType = Awaited<ReturnType<_DeletePackageCfg['execute']>>;
export const deletePackage = createCaller<DeletePackageInputType, DeletePackageOutputType>('deletePackage');

type _DeletePassengerCfg = typeof _DeletePassengerEp;
export type DeletePassengerInputType = NonNullable<_DeletePassengerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeletePassengerCfg['execute']>[0]['input'];
export type DeletePassengerOutputType = Awaited<ReturnType<_DeletePassengerCfg['execute']>>;
export const deletePassenger = createCaller<DeletePassengerInputType, DeletePassengerOutputType>('deletePassenger');

type _DeletePaymentCfg = typeof _DeletePaymentEp;
export type DeletePaymentInputType = NonNullable<_DeletePaymentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeletePaymentCfg['execute']>[0]['input'];
export type DeletePaymentOutputType = Awaited<ReturnType<_DeletePaymentCfg['execute']>>;
export const deletePayment = createCaller<DeletePaymentInputType, DeletePaymentOutputType>('deletePayment');

type _DeleteReviewCfg = typeof _DeleteReviewEp;
export type DeleteReviewInputType = NonNullable<_DeleteReviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteReviewCfg['execute']>[0]['input'];
export type DeleteReviewOutputType = Awaited<ReturnType<_DeleteReviewCfg['execute']>>;
export const deleteReview = createCaller<DeleteReviewInputType, DeleteReviewOutputType>('deleteReview');

type _DeleteTransportationCfg = typeof _DeleteTransportationEp;
export type DeleteTransportationInputType = NonNullable<_DeleteTransportationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteTransportationCfg['execute']>[0]['input'];
export type DeleteTransportationOutputType = Awaited<ReturnType<_DeleteTransportationCfg['execute']>>;
export const deleteTransportation = createCaller<DeleteTransportationInputType, DeleteTransportationOutputType>('deleteTransportation');

type _GetAccommodationsCfg = typeof _GetAccommodationsEp;
export type GetAccommodationsInputType = NonNullable<_GetAccommodationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetAccommodationsCfg['execute']>[0]['input'];
export type GetAccommodationsOutputType = Awaited<ReturnType<_GetAccommodationsCfg['execute']>>;
export const getAccommodations = createCaller<GetAccommodationsInputType, GetAccommodationsOutputType>('getAccommodations');

type _GetBookingsCfg = typeof _GetBookingsEp;
export type GetBookingsInputType = NonNullable<_GetBookingsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetBookingsCfg['execute']>[0]['input'];
export type GetBookingsOutputType = Awaited<ReturnType<_GetBookingsCfg['execute']>>;
export const getBookings = createCaller<GetBookingsInputType, GetBookingsOutputType>('getBookings');

type _GetBookingsAndCustomersCfg = typeof _GetBookingsAndCustomersEp;
export type GetBookingsAndCustomersInputType = NonNullable<_GetBookingsAndCustomersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetBookingsAndCustomersCfg['execute']>[0]['input'];
export type GetBookingsAndCustomersOutputType = Awaited<ReturnType<_GetBookingsAndCustomersCfg['execute']>>;
export const getBookingsAndCustomers = createCaller<GetBookingsAndCustomersInputType, GetBookingsAndCustomersOutputType>('getBookingsAndCustomers');

type _GetCustomersCfg = typeof _GetCustomersEp;
export type GetCustomersInputType = NonNullable<_GetCustomersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCustomersCfg['execute']>[0]['input'];
export type GetCustomersOutputType = Awaited<ReturnType<_GetCustomersCfg['execute']>>;
export const getCustomers = createCaller<GetCustomersInputType, GetCustomersOutputType>('getCustomers');

type _GetDashboardDataCfg = typeof _GetDashboardDataEp;
export type GetDashboardDataInputType = NonNullable<_GetDashboardDataCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetDashboardDataCfg['execute']>[0]['input'];
export type GetDashboardDataOutputType = Awaited<ReturnType<_GetDashboardDataCfg['execute']>>;
export const getDashboardData = createCaller<GetDashboardDataInputType, GetDashboardDataOutputType>('getDashboardData');

type _GetDestinationsCfg = typeof _GetDestinationsEp;
export type GetDestinationsInputType = NonNullable<_GetDestinationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetDestinationsCfg['execute']>[0]['input'];
export type GetDestinationsOutputType = Awaited<ReturnType<_GetDestinationsCfg['execute']>>;
export const getDestinations = createCaller<GetDestinationsInputType, GetDestinationsOutputType>('getDestinations');

type _GetIncomeDataCfg = typeof _GetIncomeDataEp;
export type GetIncomeDataInputType = NonNullable<_GetIncomeDataCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetIncomeDataCfg['execute']>[0]['input'];
export type GetIncomeDataOutputType = Awaited<ReturnType<_GetIncomeDataCfg['execute']>>;
export const getIncomeData = createCaller<GetIncomeDataInputType, GetIncomeDataOutputType>('getIncomeData');

type _GetPackagesCfg = typeof _GetPackagesEp;
export type GetPackagesInputType = NonNullable<_GetPackagesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPackagesCfg['execute']>[0]['input'];
export type GetPackagesOutputType = Awaited<ReturnType<_GetPackagesCfg['execute']>>;
export const getPackages = createCaller<GetPackagesInputType, GetPackagesOutputType>('getPackages');

type _GetPassengersCfg = typeof _GetPassengersEp;
export type GetPassengersInputType = NonNullable<_GetPassengersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPassengersCfg['execute']>[0]['input'];
export type GetPassengersOutputType = Awaited<ReturnType<_GetPassengersCfg['execute']>>;
export const getPassengers = createCaller<GetPassengersInputType, GetPassengersOutputType>('getPassengers');

type _GetPaymentsCfg = typeof _GetPaymentsEp;
export type GetPaymentsInputType = NonNullable<_GetPaymentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPaymentsCfg['execute']>[0]['input'];
export type GetPaymentsOutputType = Awaited<ReturnType<_GetPaymentsCfg['execute']>>;
export const getPayments = createCaller<GetPaymentsInputType, GetPaymentsOutputType>('getPayments');

type _GetPaymentsAndBookingsCfg = typeof _GetPaymentsAndBookingsEp;
export type GetPaymentsAndBookingsInputType = NonNullable<_GetPaymentsAndBookingsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPaymentsAndBookingsCfg['execute']>[0]['input'];
export type GetPaymentsAndBookingsOutputType = Awaited<ReturnType<_GetPaymentsAndBookingsCfg['execute']>>;
export const getPaymentsAndBookings = createCaller<GetPaymentsAndBookingsInputType, GetPaymentsAndBookingsOutputType>('getPaymentsAndBookings');

type _GetReportsDataCfg = typeof _GetReportsDataEp;
export type GetReportsDataInputType = NonNullable<_GetReportsDataCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetReportsDataCfg['execute']>[0]['input'];
export type GetReportsDataOutputType = Awaited<ReturnType<_GetReportsDataCfg['execute']>>;
export const getReportsData = createCaller<GetReportsDataInputType, GetReportsDataOutputType>('getReportsData');

type _GetReviewsCfg = typeof _GetReviewsEp;
export type GetReviewsInputType = NonNullable<_GetReviewsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetReviewsCfg['execute']>[0]['input'];
export type GetReviewsOutputType = Awaited<ReturnType<_GetReviewsCfg['execute']>>;
export const getReviews = createCaller<GetReviewsInputType, GetReviewsOutputType>('getReviews');

type _GetTransportationCfg = typeof _GetTransportationEp;
export type GetTransportationInputType = NonNullable<_GetTransportationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetTransportationCfg['execute']>[0]['input'];
export type GetTransportationOutputType = Awaited<ReturnType<_GetTransportationCfg['execute']>>;
export const getTransportation = createCaller<GetTransportationInputType, GetTransportationOutputType>('getTransportation');

type _ImportLegacyCustomersCfg = typeof _ImportLegacyCustomersEp;
export type ImportLegacyCustomersInputType = NonNullable<_ImportLegacyCustomersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ImportLegacyCustomersCfg['execute']>[0]['input'];
export type ImportLegacyCustomersOutputType = Awaited<ReturnType<_ImportLegacyCustomersCfg['execute']>>;
export const importLegacyCustomers = createCaller<ImportLegacyCustomersInputType, ImportLegacyCustomersOutputType>('importLegacyCustomers');

type _LoginCfg = typeof _LoginEp;
export type LoginInputType = NonNullable<_LoginCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_LoginCfg['execute']>[0]['input'];
export type LoginOutputType = Awaited<ReturnType<_LoginCfg['execute']>>;
export const login = createCaller<LoginInputType, LoginOutputType>('login');

type _PopulateApplicationDataCfg = typeof _PopulateApplicationDataEp;
export type PopulateApplicationDataInputType = NonNullable<_PopulateApplicationDataCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PopulateApplicationDataCfg['execute']>[0]['input'];
export type PopulateApplicationDataOutputType = Awaited<ReturnType<_PopulateApplicationDataCfg['execute']>>;
export const populateApplicationData = createCaller<PopulateApplicationDataInputType, PopulateApplicationDataOutputType>('populateApplicationData');

type _UpdateAccommodationCfg = typeof _UpdateAccommodationEp;
export type UpdateAccommodationInputType = NonNullable<_UpdateAccommodationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateAccommodationCfg['execute']>[0]['input'];
export type UpdateAccommodationOutputType = Awaited<ReturnType<_UpdateAccommodationCfg['execute']>>;
export const updateAccommodation = createCaller<UpdateAccommodationInputType, UpdateAccommodationOutputType>('updateAccommodation');

type _UpdateBookingCfg = typeof _UpdateBookingEp;
export type UpdateBookingInputType = NonNullable<_UpdateBookingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateBookingCfg['execute']>[0]['input'];
export type UpdateBookingOutputType = Awaited<ReturnType<_UpdateBookingCfg['execute']>>;
export const updateBooking = createCaller<UpdateBookingInputType, UpdateBookingOutputType>('updateBooking');

type _UpdateCustomerCfg = typeof _UpdateCustomerEp;
export type UpdateCustomerInputType = NonNullable<_UpdateCustomerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateCustomerCfg['execute']>[0]['input'];
export type UpdateCustomerOutputType = Awaited<ReturnType<_UpdateCustomerCfg['execute']>>;
export const updateCustomer = createCaller<UpdateCustomerInputType, UpdateCustomerOutputType>('updateCustomer');

type _UpdateDestinationCfg = typeof _UpdateDestinationEp;
export type UpdateDestinationInputType = NonNullable<_UpdateDestinationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateDestinationCfg['execute']>[0]['input'];
export type UpdateDestinationOutputType = Awaited<ReturnType<_UpdateDestinationCfg['execute']>>;
export const updateDestination = createCaller<UpdateDestinationInputType, UpdateDestinationOutputType>('updateDestination');

type _UpdatePackageCfg = typeof _UpdatePackageEp;
export type UpdatePackageInputType = NonNullable<_UpdatePackageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdatePackageCfg['execute']>[0]['input'];
export type UpdatePackageOutputType = Awaited<ReturnType<_UpdatePackageCfg['execute']>>;
export const updatePackage = createCaller<UpdatePackageInputType, UpdatePackageOutputType>('updatePackage');

type _UpdatePaymentCfg = typeof _UpdatePaymentEp;
export type UpdatePaymentInputType = NonNullable<_UpdatePaymentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdatePaymentCfg['execute']>[0]['input'];
export type UpdatePaymentOutputType = Awaited<ReturnType<_UpdatePaymentCfg['execute']>>;
export const updatePayment = createCaller<UpdatePaymentInputType, UpdatePaymentOutputType>('updatePayment');

type _UpdateTransportationCfg = typeof _UpdateTransportationEp;
export type UpdateTransportationInputType = NonNullable<_UpdateTransportationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateTransportationCfg['execute']>[0]['input'];
export type UpdateTransportationOutputType = Awaited<ReturnType<_UpdateTransportationCfg['execute']>>;
export const updateTransportation = createCaller<UpdateTransportationInputType, UpdateTransportationOutputType>('updateTransportation');


export const api = {
  cleanupCustomerData,
  createAccommodation,
  createBooking,
  createCustomer,
  createDestination,
  createPackage,
  createPassenger,
  createPayment,
  createReview,
  createTransportation,
  deleteAccommodation,
  deleteBooking,
  deleteCustomer,
  deleteDestination,
  deletePackage,
  deletePassenger,
  deletePayment,
  deleteReview,
  deleteTransportation,
  getAccommodations,
  getBookings,
  getBookingsAndCustomers,
  getCustomers,
  getDashboardData,
  getDestinations,
  getIncomeData,
  getPackages,
  getPassengers,
  getPayments,
  getPaymentsAndBookings,
  getReportsData,
  getReviews,
  getTransportation,
  importLegacyCustomers,
  login,
  populateApplicationData,
  updateAccommodation,
  updateBooking,
  updateCustomer,
  updateDestination,
  updatePackage,
  updatePayment,
  updateTransportation,
};
